=== ChunHungLiu/GW2Emu/GameRevision.GW2Emu.PacketGenerator/Xml/Templates.xsd
<?xml version="1.0" encoding="utf-8"?>

<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">


  <!--RootNode: Packets-->
  <xsd:element name="Templates">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element name="Protocol" type="CommunicationDirection" minOccurs="0" maxOccurs="unbounded" />
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>


  <!--Type defs-->
  <!--CommunicationDirection-->
  <xsd:complexType name="CommunicationDirection">
    <xsd:sequence>
      <xsd:element name="Packet" type="PacketType" minOccurs="0" maxOccurs="unbounded" />
    </xsd:sequence>
    <xsd:attribute name="type" type="ProtocolSimpleTypes" use="required" />
    <!--Ex: "GStoC"-->
  </xsd:complexType>


  <!--PacketType-->
  <xsd:complexType name="PacketType">
    <xsd:complexContent>
      <xsd:extension base="UserNamedType">
        <xsd:sequence>
          <xsd:element name="Field" type="BasicFieldType" minOccurs="0" maxOccurs="unbounded" />
        </xsd:sequence>
        <xsd:attribute name="header" type="xsd:integer" use="required" />
        <xsd:attribute name="typeSize" type="xsd:integer" use="required" />
        <xsd:attribute name="staticSize" type="xsd:integer" use="required" />
      </xsd:extension>
    </xsd:complexContent>
    <!--Ex: "123"-->
  </xsd:complexType>


  <!--MetaInfo-->
  <!--Hint: This type is an optional note, that can be attached to a packet template or field-->
  <xsd:complexType name="MetaInfo">
    <xsd:sequence>
      <!--Used whenever a packet or type has a special name or description-->
      <xsd:element name="Name" type="xsd:string" minOccurs="0" maxOccurs="1" />
      <xsd:element name="Description" type="xsd:string" minOccurs="0" maxOccurs="1" />
      <!--Can be used to sign packets (optional ofc)-->
      <xsd:element name="Author" type="xsd:string" minOccurs="0" maxOccurs="1" />
    </xsd:sequence>
  </xsd:complexType>

  <xsd:complexType name="UserNamedType">
    <xsd:sequence>
      <xsd:element name="Info" type="MetaInfo" minOccurs="0" maxOccurs="1" />
    </xsd:sequence>
  </xsd:complexType>

  <!--PacketFieldType-->
  <xsd:complexType name="BasicFieldType">
    <xsd:complexContent>
      <xsd:extension base="UserNamedType">
        
        <!--attribute "type" should be "nested" when we've got one or more of fields within this field-->
        <!--(in that case, the type of this field is a struct and it is directly defined within the template)-->
        <!--note that (by this definition) it is allowed to have nested structs in a nested struct-->
        <xsd:attribute name="type" type="PacketSimpleTypes" use="required" />

        <xsd:attribute name="static" type="xsd:boolean" use="optional" />
      </xsd:extension>
    </xsd:complexContent>
  </xsd:complexType>


  <xsd:complexType name="StructFieldType">
    <xsd:complexContent>
      <xsd:extension base="BasicFieldType">
        <xsd:sequence>
          <xsd:element name="Field" type="BasicFieldType" minOccurs="0" maxOccurs="unbounded" />
        </xsd:sequence>
        <xsd:attribute name="typeSize" type="xsd:integer" use="required" />
        <xsd:attribute name="staticSize" type="xsd:integer" use="required" />
      </xsd:extension>

    </xsd:complexContent>
  </xsd:complexType>

  <xsd:complexType name="StaticArrayFieldType">
    <xsd:complexContent>
      <xsd:extension base="StructFieldType">
        <xsd:attribute name="elements" type="xsd:unsignedInt" use="required" />
      </xsd:extension>
    </xsd:complexContent>
  </xsd:complexType>

  <xsd:complexType name="VarByteType">
    <xsd:complexContent>
      <xsd:extension base="BasicFieldType">
        <xsd:attribute name="srcBytes" type="xsd:integer" use="required" />
        <xsd:attribute name="destBytes" type="xsd:integer" use="required" />
      </xsd:extension>
    </xsd:complexContent>
  </xsd:complexType>
  
  <!--PacketSimpleTypes-->
  <xsd:simpleType name="PacketSimpleTypes">
    <xsd:restriction base="xsd:string">
      <xsd:enumeration value="byte" />
      <!--8 Bit-->
      <xsd:enumeration value="short" />
      <!--16 Bit-->
      <xsd:enumeration value="long" />
      <!--64 Bit-->
      <xsd:enumeration value="varint" />
      <!--variable length (packed) number-->
      <xsd:enumeration value="float" />
      <!--32 Bit-->
      <xsd:enumeration value="vec2" />
      <!--64 Bit-->
      <xsd:enumeration value="vec3" />
      <!--96 Bit-->
      <xsd:enumeration value="vec4" />
      <!--128 Bit-->
      <xsd:enumeration value="dw3" />
      <!--96 Bit-->
      <xsd:enumeration value="uid16" />
      <!--16 Byte-->
      <xsd:enumeration value="guid18" />
      <!--18 Byte-->
      <xsd:enumeration value="ascii" />
      <!--8 Bit-->
      <xsd:enumeration value="utf16" />
      <!--16 Bit-->
      <xsd:enumeration value="optional" />
      <!--1 Byte + nested-->
      <xsd:enumeration value="array_static" />
      <!--Nested fixed sized array-->
      <xsd:enumeration value="array_var_small" />
      <!--1 Byte (lenght) + array-->
      <xsd:enumeration value="array_var_big" />
      <!--2 Byte (lenght) + array-->
      <xsd:enumeration value="buffer_static" />
      <!--Nested fixed sized buffer-->
      <xsd:enumeration value="buffer_var_small" />
      <!--1 Byte (lenght) + array-->
      <xsd:enumeration value="buffer_var_big" />
      <!--2 Byte (lenght) + array-->
      <xsd:enumeration value="varbyte" />
      <!--1 to 8 Bytes-->
    </xsd:restriction>
  </xsd:simpleType>

  <xsd:simpleType name="ProtocolSimpleTypes">
    <xsd:restriction base="xsd:string">
      <xsd:enumeration value="CtoLS" />
      <xsd:enumeration value="CtoGS" />
      <xsd:enumeration value="LStoC" />
      <xsd:enumeration value="GStoC" />
    </xsd:restriction>
  </xsd:simpleType>

</xsd:schema>

=== ChunHungLiu/GW2Emu/GameRevision.GW2Emu.CodeWriter/Xml/Templates.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>

<Templates xmlns:gw2="http://www.gamerevision.com/xsd/gw2" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:schemaLocation="http://www.gamerevision.com/xsd/gw2 http://www.gamerevision.com/xsd/gw2/templates.xsd">

  <Protocol type="CtoLS">
    <Packet header="1" staticSize="7" typeSize="6">
      <Field type="varint" />
    </Packet>
    <Packet header="2" staticSize="74" typeSize="10">
      <Field type="utf16" />
      <Field type="utf16" />
    </Packet>
    <Packet header="3" staticSize="27" typeSize="10">
      <Field type="varint" />
      <Field elements="16" staticSize="20" type="buffer_static" typeSize="0" xsi:type="StaticArrayFieldType" />
    </Packet>
    <Packet header="4" staticSize="119" typeSize="23">
      <Field staticSize="101" type="buffer_var_small" typeSize="0" xsi:type="StructFieldType" />
      <Field type="uid16" />
    </Packet>
    <Packet header="5" staticSize="7" typeSize="6">
      <Field type="varint" />
    </Packet>
    <Packet header="10" staticSize="107" typeSize="42">
      <Field type="varint" />
      <Field type="uid16" />
      <Field type="uid16" />
      <Field type="utf16" />
    </Packet>
    <Packet header="11" staticSize="7" typeSize="6">
      <Field type="varint" />
    </Packet>
    <Packet header="12" staticSize="4109" typeSize="12">
      <Field type="varint" />
      <Field staticSize="4102" type="buffer_var_big" typeSize="0" xsi:type="StructFieldType" />
    </Packet>
    <Packet header="14" staticSize="13" typeSize="11">
      <Field type="varint" />
      <Field type="varint" />
      <Field type="byte" />
    </Packet>
    <Packet header="15" staticSize="3" typeSize="3">
      <Field type="byte" />
    </Packet>
    <Packet header="16" staticSize="17" typeSize="14">
      <Field type="varint" />
      <Field type="varint" />
      <Field type="varint" />
    </Packet>
    <Packet header="20" staticSize="31" typeSize="10">
      <Field type="varint" />
      <Field type="utf16" />
    </Packet>
    <Packet header="21" staticSize="47" typeSize="26">
      <Field type="varint" />
      <Field type="uid16" />
      <Field type="utf16" />
    </Packet>
    <Packet header="22" staticSize="31" typeSize="10">
      <Field type="varint" />
      <Field type="utf16" />
    </Packet>
    <Packet header="23" staticSize="548" typeSize="15">
      <Field type="varint" />
      <Field type="utf16" />
      <Field staticSize="517" type="buffer_var_small" typeSize="0" xsi:type="StructFieldType" />
    </Packet>
    <Packet header="24" staticSize="55" typeSize="14">
      <Field type="varint" />
      <Field type="utf16" />
      <Field type="utf16" />
    </Packet>
    <Packet header="25" staticSize="7" typeSize="6">
      <Field type="varint" />
    </Packet>
    <Packet header="26" staticSize="7" typeSize="6">
      <Field type="varint" />
    </Packet>
    <Packet header="29" staticSize="27" typeSize="22">
      <Field type="varint" />
      <Field type="varint" />
      <Field type="varint" />
      <Field type="varint" />
      <Field type="varint" />
    </Packet>
    <Packet header="34" staticSize="7" typeSize="6">
      <Field type="varint" />
    </Packet>
    <Packet header="35" staticSize="2" typeSize="2" />
    <Packet header="36" staticSize="48" typeSize="14">
      <Field type="varint" />
      <Field type="varint" />
      <Field type="utf16" />
    </Packet>
  </Protocol>

  <Protocol type="CtoGS">
    <Packet header="1" staticSize="2" typeSize="2" />
    <Packet header="2" staticSize="7" typeSize="6">
      <Field type="varint" />
    </Packet>
    <Packet header="3" staticSize="10" typeSize="9">
      <Field type="short" />
      <Field type="varint" />
      <Field type="byte" />
    </Packet>
    <Packet header="4" staticSize="50" typeSize="48">
      <Field type="short" />
      <Field type="varint" />
      <Field type="byte" />
      <Field type="vec4" />
      <Field type="varint" />
      <Field type="vec4" />
      <Field type="byte" />
      <Field type="byte" />
      <Field type="byte" />
    </Packet>
    <Packet header="5" staticSize="102" typeSize="20">
      <Field type="short" />
      <Field type="varint" />
      <Field type="byte" />
      <Field type="varint" />
      <Field staticSize="85" type="buffer_var_small" typeSize="0" xsi:type="StructFieldType" />
      <Field type="short" />
    </Packet>
    <Packet header="6" staticSize="150" typeSize="51">
      <Field type="short" />
      <Field type="varint" />
      <Field type="byte" />
      <Field type="varint" />
      <Field staticSize="85" type="buffer_var_small" typeSize="0" xsi:type="StructFieldType" />
      <Field type="vec4" />
      <Field type="varint" />
      <Field staticSize="20" type="optional" typeSize="16" xsi:type="StructFieldType">
        <Field type="vec4" />
      </Field>
      <Field type="byte" />
      <Field type="byte" />
      <Field type="byte" />
      <Field type="short" />
      <Field type="short" />
      <Field type="short" />
    </Packet>
    <Packet header="7" staticSize="140" typeSize="57">
      <Field type="short" />
      <Field type="varint" />
      <Field type="byte" />
      <Field type="varint" />
      <Field staticSize="85" type="buffer_var_small" typeSize="0" xsi:type="StructFieldType" />
      <Field type="vec4" />
      <Field type="varint" />
      <Field type="vec4" />
      <Field type="byte" />
      <Field type="byte" />
      <Field type="byte" />
    </Packet>
    <Packet header="8" staticSize="191" typeSize="77">
      <Field type="short" />
      <Field type="varint" />
      <Field type="byte" />
      <Field type="varint" />
      <Field staticSize="85" type="buffer_var_small" typeSize="0" xsi:type="StructFieldType" />
      <Field type="vec4" />
      <Field type="varint" />
      <Field type="vec4" />
      <Field type="byte" />
      <Field type="byte" />
      <Field type="byte" />
      <Field type="vec3" />
      <Field type="short" />
      <Field type="short" />
      <Field staticSize="35" type="optional" typeSize="12" xsi:type="StructFieldType">
        <Field type="varint" />
        <Field type="varint" />
        <Field staticSize="21" type="optional" typeSize="16" xsi:type="StructFieldType">
          <Field type="dw3" />
        </Field>
      </Field>
    </Packet>
    <Packet header="9" staticSize="108" typeSize="26">
      <Field type="short" />
      <Field type="varint" />
      <Field type="byte" />
      <Field type="varint" />
      <Field staticSize="85" type="buffer_var_small" typeSize="0" xsi:type="StructFieldType" />
      <Field type="float" />
      <Field type="short" />
      <Field type="short" />
    </Packet>
    <Packet header="10" staticSize="122" typeSize="39">
      <Field type="short" />
      <Field type="varint" />
      <Field type="byte" />
      <Field type="varint" />
      <Field staticSize="85" type="buffer_var_small" typeSize="0" xsi:type="StructFieldType" />
      <Field type="dw3" />
      <Field type="short" />
      <Field type="short" />
      <Field type="byte" />
    </Packet>
    <Packet header="11" staticSize="15" typeSize="14">
      <Field type="short" />
      <Field type="varint" />
      <Field type="byte" />
      <Field type="byte" />
      <Field type="float" />
    </Packet>
    <Packet header="12" staticSize="4" typeSize="4">
      <Field type="short" />
    </Packet>
    <Packet header="13" staticSize="31" typeSize="28">
      <Field type="varint" />
      <Field type="varint" />
      <Field type="vec3" />
      <Field type="varint" />
      <Field type="byte" />
      <Field type="byte" />
    </Packet>
    <Packet header="14" staticSize="104" typeSize="22">
      <Field type="short" />
      <Field type="varint" />
      <Field type="byte" />
      <Field type="varint" />
      <Field staticSize="85" type="buffer_var_small" typeSize="0" xsi:type="StructFieldType" />
      <Field type="short" />
      <Field type="short" />
    </Packet>
    <Packet header="15" staticSize="100" typeSize="18">
      <Field type="short" />
      <Field type="varint" />
      <Field type="byte" />
      <Field type="varint" />
      <Field staticSize="85" type="buffer_var_small" typeSize="0" xsi:type="StructFieldType" />
    </Packet>
    <Packet header="16" staticSize="27" typeSize="25">
      <Field type="short" />
      <Field type="varint" />
      <Field type="byte" />
      <Field type="dw3" />
    </Packet>
    <Packet header="17" staticSize="7" typeSize="6">
      <Field type="varint" />
    </Packet>
    <Packet header="18" staticSize="7" typeSize="6">
      <Field type="varint" />
    </Packet>
    <Packet header="19" staticSize="2" typeSize="2" />
    <Packet header="20" staticSize="12" typeSize="11">
      <Field type="short" />
      <Field type="short" />
      <Field type="varint" />
      <Field type="byte" />
    </Packet>
    <Packet header="21" staticSize="10" typeSize="10">
      <Field type="short" />
      <Field type="short" />
      <Field type="byte" />
      <Field type="short" />
      <Field type="byte" />
    </Packet>
    <Packet header="22" staticSize="12" typeSize="11">
      <Field type="short" />
      <Field type="short" />
      <Field type="varint" />
      <Field type="byte" />
    </Packet>
    <Packet header="23" staticSize="12" typeSize="11">
      <Field type="short" />
      <Field type="short" />
      <Field type="varint" />
      <Field type="byte" />
    </Packet>
    <Packet header="24" staticSize="2" typeSize="2" />
    <Packet header="25" staticSize="12" typeSize="10">
      <Field type="varint" />
      <Field type="varint" />
    </Packet>
    <Packet header="26" staticSize="2" typeSize="2" />
    <Packet header="28" staticSize="7" typeSize="6">
      <Field type="varint" />
    </Packet>
    <Packet header="29" staticSize="2" typeSize="2" />
    <Packet header="30" staticSize="31" typeSize="10">
